/**
 * Deterministic demo data.
 *
 * Used by the mock adapter when the backend API is not reachable, so the
 * frontend is fully demoable on its own. Values are fixed (no `Math.random`)
 * to keep screenshots and manual QA stable between reloads.
 */

import {
  REQUEST_STATUS,
  ROLES,
  VERIFICATION_STATUS,
  ACCOUNT_STATUS,
  NOTIFICATION_TYPE,
  REPORT_REASON,
} from '../../../shared/constants.js';

/** Fixed clock so relative timestamps stay sensible regardless of build date. */
const NOW = new Date();
const hoursFromNow = (hours) => new Date(NOW.getTime() + hours * 3_600_000).toISOString();
const daysFromNow = (days) => {
  const date = new Date(NOW);
  date.setDate(date.getDate() + days);
  return date.toISOString().slice(0, 10);
};

export const demoUser = {
  id: 'USR-0001',
  fullName: 'Chidi Okonkwo',
  email: 'chidi@example.com',
  phone: '+2348031234567',
  state: 'Anambra',
  city: 'Awka',
  area: 'Umuoji',
  role: ROLES.CUSTOMER,
  status: ACCOUNT_STATUS.ACTIVE,
  avatarUrl: null,
  createdAt: hoursFromNow(-24 * 60),
};

export const demoProviderUser = {
  id: 'USR-0101',
  fullName: 'John Plumbing Services',
  email: 'john@example.com',
  phone: '+2348069988776',
  role: ROLES.PROVIDER,
  status: ACCOUNT_STATUS.ACTIVE,
  avatarUrl: null,
  createdAt: hoursFromNow(-24 * 200),
};

/* ------------------------------------------------------------------ */
/* Providers                                                           */
/* ------------------------------------------------------------------ */

export const providers = [
  {
    id: 'PRV-001',
    userId: 'USR-0101',
    businessName: 'John Plumbing Services',
    fullName: 'John Okafor',
    serviceCategory: 'plumber',
    categories: ['plumber'],
    bio: 'Licensed plumber with 8 years of experience handling residential and light commercial work across Awka. I specialise in leak diagnosis, pipe installation and water heater servicing, and I always arrive with the common parts in stock.',
    state: 'Anambra',
    city: 'Awka',
    areas: ['Umuoji', 'Amakwo', 'Okuku'],
    experienceYears: 8,
    rating: 4.8,
    reviewCount: 34,
    completedJobs: 212,
    verificationStatus: VERIFICATION_STATUS.VERIFIED,
    available: true,
    responseTime: 'Usually responds within 20 minutes',
    services: [
      { id: 'SVC-001', name: 'Leak Repair', description: 'Kitchen, bathroom and outdoor leak diagnosis and repair.' },
      { id: 'SVC-002', name: 'Pipe Installation', description: 'New pipe installation for homes and small businesses.' },
      { id: 'SVC-003', name: 'Water Heater', description: 'Water heater repair, replacement and installation.' },
      { id: 'SVC-004', name: 'Drainage Clearing', description: 'Blocked drain and septic clearing.' },
    ],
    availability: [
      { day: 1, available: true, start: '08:00', end: '17:00' },
      { day: 2, available: true, start: '08:00', end: '17:00' },
      { day: 3, available: true, start: '08:00', end: '17:00' },
      { day: 4, available: true, start: '08:00', end: '17:00' },
      { day: 5, available: true, start: '08:00', end: '17:00' },
      { day: 6, available: true, start: '09:00', end: '14:00' },
      { day: 0, available: false, start: null, end: null },
    ],
  },
  {
    id: 'PRV-002',
    userId: 'USR-0102',
    businessName: 'XYZ Plumbing',
    fullName: 'Ada Nwosu',
    serviceCategory: 'plumber',
    categories: ['plumber'],
    bio: 'Fast, tidy plumbing work for landlords and property managers. Same-day attendance for urgent leaks and overflowing cisterns.',
    state: 'Anambra',
    city: 'Awka',
    areas: ['Umuoji', 'Nri'],
    experienceYears: 5,
    rating: 4.5,
    reviewCount: 19,
    completedJobs: 88,
    verificationStatus: VERIFICATION_STATUS.VERIFIED,
    available: true,
    responseTime: 'Usually responds within 1 hour',
    services: [
      { id: 'SVC-005', name: 'Leak Repair', description: 'Urgent leak and burst pipe repair.' },
      { id: 'SVC-006', name: 'Cistern Replacement', description: 'Flush cistern and toilet replacement.' },
    ],
    availability: [
      { day: 1, available: true, start: '07:00', end: '18:00' },
      { day: 2, available: true, start: '07:00', end: '18:00' },
      { day: 3, available: true, start: '07:00', end: '18:00' },
      { day: 4, available: true, start: '07:00', end: '18:00' },
      { day: 5, available: true, start: '07:00', end: '18:00' },
      { day: 6, available: false, start: null, end: null },
      { day: 0, available: false, start: null, end: null },
    ],
  },
  {
    id: 'PRV-003',
    userId: 'USR-0103',
    businessName: 'ABC Electric',
    fullName: 'Emeka Obi',
    serviceCategory: 'electrician',
    categories: ['electrician', 'ac-technician'],
    bio: 'Electrician and AC technician. I handle wiring, DB board upgrades, socket faults, and air conditioner servicing. Safety certificate on file.',
    state: 'Anambra',
    city: 'Awka',
    areas: ['Umuoji', 'Amakwo', 'Eziama'],
    experienceYears: 11,
    rating: 4.9,
    reviewCount: 57,
    completedJobs: 341,
    verificationStatus: VERIFICATION_STATUS.VERIFIED,
    available: true,
    responseTime: 'Usually responds within 10 minutes',
    services: [
      { id: 'SVC-007', name: 'Wiring & Rewiring', description: 'Full house rewiring and new circuit installation.' },
      { id: 'SVC-008', name: 'AC Servicing', description: 'Air conditioner gas refill, cleaning and repair.' },
      { id: 'SVC-009', name: 'Lighting & Sockets', description: 'Fitting and fault-finding for lights and sockets.' },
    ],
    availability: [
      { day: 1, available: true, start: '08:00', end: '18:00' },
      { day: 2, available: true, start: '08:00', end: '18:00' },
      { day: 3, available: true, start: '08:00', end: '18:00' },
      { day: 4, available: true, start: '08:00', end: '18:00' },
      { day: 5, available: true, start: '08:00', end: '18:00' },
      { day: 6, available: true, start: '09:00', end: '15:00' },
      { day: 0, available: false, start: null, end: null },
    ],
  },
  {
    id: 'PRV-004',
    userId: 'USR-0104',
    businessName: 'Bright Spark Tutors',
    fullName: 'Grace Uche',
    serviceCategory: 'tutor',
    categories: ['tutor', 'language-teacher'],
    bio: 'Certified secondary and primary school tutor with 6 years of experience. Maths, English and Basic Science. Home and online lessons.',
    state: 'Anambra',
    city: 'Awka',
    areas: ['Umuoji'],
    experienceYears: 6,
    rating: 4.7,
    reviewCount: 26,
    completedJobs: 140,
    verificationStatus: VERIFICATION_STATUS.VERIFIED,
    available: true,
    responseTime: 'Usually responds within 2 hours',
    services: [
      { id: 'SVC-010', name: 'Mathematics Tutoring', description: 'Primary to secondary school mathematics.' },
      { id: 'SVC-011', name: 'English Tutoring', description: 'Comprehension, grammar and exam preparation.' },
      { id: 'SVC-012', name: 'Exam Preparation', description: 'JAMB and WAEC preparation.' },
    ],
    availability: [
      { day: 1, available: true, start: '16:00', end: '20:00' },
      { day: 2, available: true, start: '16:00', end: '20:00' },
      { day: 3, available: true, start: '16:00', end: '20:00' },
      { day: 4, available: true, start: '16:00', end: '20:00' },
      { day: 5, available: true, start: '16:00', end: '20:00' },
      { day: 6, available: true, start: '09:00', end: '13:00' },
      { day: 0, available: false, start: null, end: null },
    ],
  },
  {
    id: 'PRV-005',
    userId: 'USR-0105',
    businessName: 'SparkleHome Cleaning',
    fullName: 'Jane Eze',
    serviceCategory: 'cleaner',
    categories: ['cleaner'],
    bio: 'Deep cleaning, move-in and move-out cleaning, and regular weekly visits. I bring my own supplies and a team for larger homes.',
    state: 'Anambra',
    city: 'Awka',
    areas: ['Umuoji', 'Amakwo', 'Nri'],
    experienceYears: 4,
    rating: 4.6,
    reviewCount: 41,
    completedJobs: 176,
    verificationStatus: VERIFICATION_STATUS.VERIFIED,
    available: true,
    responseTime: 'Usually responds within 45 minutes',
    services: [
      { id: 'SVC-013', name: 'Deep Cleaning', description: 'Full home deep clean including kitchen and bathrooms.' },
      { id: 'SVC-014', name: 'Move In / Out', description: 'Cleaning before moving in or after vacating.' },
      { id: 'SVC-015', name: 'Weekly Cleaning', description: 'Recurring weekly or fortnightly visits.' },
    ],
    availability: [
      { day: 1, available: true, start: '09:00', end: '17:00' },
      { day: 2, available: true, start: '09:00', end: '17:00' },
      { day: 3, available: true, start: '09:00', end: '17:00' },
      { day: 4, available: true, start: '09:00', end: '17:00' },
      { day: 5, available: true, start: '09:00', end: '17:00' },
      { day: 6, available: true, start: '10:00', end: '14:00' },
      { day: 0, available: false, start: null, end: null },
    ],
  },
  {
    id: 'PRV-006',
    userId: 'USR-0106',
    businessName: 'Ogunleye Motors',
    fullName: 'Tunde Ogunleye',
    serviceCategory: 'mechanic',
    categories: ['mechanic', 'auto-electrician'],
    bio: 'Mobile mechanic and auto electrician. I come to your home or office with diagnostics and common spares. Also does tyre fitting and balancing.',
    state: 'Anambra',
    city: 'Awka',
    areas: ['Umuoji', 'Eziama'],
    experienceYears: 14,
    rating: 4.4,
    reviewCount: 63,
    completedJobs: 428,
    verificationStatus: VERIFICATION_STATUS.UNVERIFIED,
    available: false,
    responseTime: 'Usually responds within 3 hours',
    services: [
      { id: 'SVC-016', name: 'Car Diagnosis', description: 'Engine, transmission and electrical fault diagnosis.' },
      { id: 'SVC-017', name: 'Tyre Fitting', description: 'Tyre fitting, balancing and puncture repair.' },
      { id: 'SVC-018', name: 'Full Servicing', description: 'Periodic maintenance and oil change.' },
    ],
    availability: [
      { day: 1, available: true, start: '08:00', end: '18:00' },
      { day: 2, available: true, start: '08:00', end: '18:00' },
      { day: 3, available: true, start: '08:00', end: '18:00' },
      { day: 4, available: true, start: '08:00', end: '18:00' },
      { day: 5, available: true, start: '08:00', end: '18:00' },
      { day: 6, available: false, start: null, end: null },
      { day: 0, available: false, start: null, end: null },
    ],
  },
  {
    id: 'PRV-007',
    userId: 'USR-0107',
    businessName: 'Lagos Fix Mobile Repairs',
    fullName: 'Segun Adeyemi',
    serviceCategory: 'phone-technician',
    categories: ['phone-technician', 'laptop', 'computer-technician'],
    bio: 'Phone, laptop and computer repairs with same-day turnaround. Screen, battery, board-level and software fixes.',
    state: 'Lagos',
    city: 'Ikeja',
    areas: ['Ikeja', 'Yaba'],
    experienceYears: 9,
    rating: 4.9,
    reviewCount: 112,
    completedJobs: 610,
    verificationStatus: VERIFICATION_STATUS.VERIFIED,
    available: true,
    responseTime: 'Usually responds within 15 minutes',
    services: [
      { id: 'SVC-019', name: 'Phone Screen Repair', description: 'Screen and digitiser replacement.' },
      { id: 'SVC-020', name: 'Laptop Repair', description: 'Hardware and software troubleshooting.' },
    ],
    availability: [
      { day: 1, available: true, start: '09:00', end: '19:00' },
      { day: 2, available: true, start: '09:00', end: '19:00' },
      { day: 3, available: true, start: '09:00', end: '19:00' },
      { day: 4, available: true, start: '09:00', end: '19:00' },
      { day: 5, available: true, start: '09:00', end: '19:00' },
      { day: 6, available: true, start: '10:00', end: '16:00' },
      { day: 0, available: false, start: null, end: null },
    ],
  },
  {
    id: 'PRV-008',
    userId: 'USR-0108',
    businessName: 'Abuja HomePro Painters',
    fullName: 'Ibrahim Musa',
    serviceCategory: 'painter',
    categories: ['painter'],
    bio: 'Interior and exterior painting, wall repair and finishing. Free quotation after a site visit.',
    state: 'Abuja',
    city: 'Gwagwalada',
    areas: ['Gwagwalada', 'Maitama'],
    experienceYears: 12,
    rating: 4.3,
    reviewCount: 28,
    completedJobs: 155,
    verificationStatus: VERIFICATION_STATUS.VERIFIED,
    available: true,
    responseTime: 'Usually responds within 2 hours',
    services: [
      { id: 'SVC-021', name: 'Interior Painting', description: 'Interior repainting and finishing.' },
      { id: 'SVC-022', name: 'Exterior Painting', description: 'Exterior painting and weatherproofing.' },
    ],
    availability: [
      { day: 1, available: true, start: '07:30', end: '16:30' },
      { day: 2, available: true, start: '07:30', end: '16:30' },
      { day: 3, available: true, start: '07:30', end: '16:30' },
      { day: 4, available: true, start: '07:30', end: '16:30' },
      { day: 5, available: true, start: '07:30', end: '16:30' },
      { day: 6, available: false, start: null, end: null },
      { day: 0, available: false, start: null, end: null },
    ],
  },
];

/* ------------------------------------------------------------------ */
/* Service requests                                                    */
/* ------------------------------------------------------------------ */

export const serviceRequests = [
  {
    id: 'REQ-00124',
    customerId: demoUser.id,
    customerName: demoUser.fullName,
    providerId: 'PRV-001',
    providerName: 'John Plumbing Services',
    serviceId: 'SVC-001',
    serviceName: 'Leak Repair',
    categoryId: 'plumber',
    description: 'Kitchen sink is leaking underneath the cabinet. Water pools when the tap runs.',
    state: 'Anambra',
    city: 'Awka',
    area: 'Umuoji',
    preferredDate: daysFromNow(3),
    preferredTime: '10:00',
    status: REQUEST_STATUS.ACCEPTED,
    createdAt: hoursFromNow(-6),
    updatedAt: hoursFromNow(-5),
    rejectionReason: null,
    notes: 'Please call before arriving.',
    imageUrl: null,
  },
  {
    id: 'REQ-00119',
    customerId: demoUser.id,
    customerName: demoUser.fullName,
    providerId: 'PRV-003',
    providerName: 'ABC Electric',
    serviceId: 'SVC-009',
    serviceName: 'Lighting & Sockets',
    categoryId: 'electrician',
    description: 'Living room sockets spark when the air conditioner is switched on.',
    state: 'Anambra',
    city: 'Awka',
    area: 'Umuoji',
    preferredDate: daysFromNow(6),
    preferredTime: '14:00',
    status: REQUEST_STATUS.PENDING,
    createdAt: hoursFromNow(-2),
    updatedAt: hoursFromNow(-2),
    rejectionReason: null,
    notes: '',
    imageUrl: null,
  },
  {
    id: 'REQ-00102',
    customerId: demoUser.id,
    customerName: demoUser.fullName,
    providerId: 'PRV-005',
    providerName: 'SparkleHome Cleaning',
    serviceId: 'SVC-014',
    serviceName: 'Move In / Out',
    categoryId: 'cleaner',
    description: 'Move-out cleaning for a 3 bedroom flat before handover.',
    state: 'Anambra',
    city: 'Awka',
    area: 'Amakwo',
    preferredDate: daysFromNow(-9),
    preferredTime: '09:00',
    status: REQUEST_STATUS.COMPLETED,
    createdAt: hoursFromNow(-24 * 12),
    updatedAt: hoursFromNow(-24 * 9),
    rejectionReason: null,
    notes: '',
    imageUrl: null,
  },
  {
    id: 'REQ-00098',
    customerId: demoUser.id,
    customerName: demoUser.fullName,
    providerId: 'PRV-002',
    providerName: 'XYZ Plumbing',
    serviceId: 'SVC-005',
    serviceName: 'Leak Repair',
    categoryId: 'plumber',
    description: 'Bathroom cistern overflows continuously.',
    state: 'Anambra',
    city: 'Awka',
    area: 'Nri',
    preferredDate: daysFromNow(-24),
    preferredTime: '15:00',
    status: REQUEST_STATUS.CANCELLED,
    createdAt: hoursFromNow(-24 * 28),
    updatedAt: hoursFromNow(-24 * 26),
    rejectionReason: null,
    notes: '',
    imageUrl: null,
  },
  {
    id: 'REQ-00131',
    customerId: 'USR-0301',
    customerName: 'Ada Nwosu',
    providerId: 'PRV-001',
    providerName: 'John Plumbing Services',
    serviceId: 'SVC-002',
    serviceName: 'Pipe Installation',
    categoryId: 'plumber',
    description: 'Need new PVC pipes laid for a borehole to the kitchen.',
    state: 'Anambra',
    city: 'Awka',
    area: 'Amakwo',
    preferredDate: daysFromNow(2),
    preferredTime: '08:00',
    status: REQUEST_STATUS.PENDING,
    createdAt: hoursFromNow(-1),
    updatedAt: hoursFromNow(-1),
    rejectionReason: null,
    notes: 'Borehole is at the back of the compound.',
    imageUrl: null,
  },
  {
    id: 'REQ-00129',
    customerId: 'USR-0302',
    customerName: 'Emeka Obi',
    providerId: 'PRV-001',
    providerName: 'John Plumbing Services',
    serviceId: 'SVC-003',
    serviceName: 'Water Heater',
    categoryId: 'plumber',
    description: 'Water heater not heating. Model is Thermocraft TC-50.',
    state: 'Anambra',
    city: 'Awka',
    area: 'Eziama',
    preferredDate: daysFromNow(4),
    preferredTime: '11:00',
    status: REQUEST_STATUS.ACCEPTED,
    createdAt: hoursFromNow(-20),
    updatedAt: hoursFromNow(-18),
    rejectionReason: null,
    notes: '',
    imageUrl: null,
  },
  {
    id: 'REQ-00125',
    customerId: 'USR-0303',
    customerName: 'Grace Uche',
    providerId: 'PRV-001',
    providerName: 'John Plumbing Services',
    serviceId: 'SVC-004',
    serviceName: 'Drainage Clearing',
    categoryId: 'plumber',
    description: 'Outside drain blocked, water backing up near the gate.',
    state: 'Anambra',
    city: 'Awka',
    area: 'Nri',
    preferredDate: daysFromNow(5),
    preferredTime: '13:00',
    status: REQUEST_STATUS.SCHEDULED,
    createdAt: hoursFromNow(-72),
    updatedAt: hoursFromNow(-48),
    rejectionReason: null,
    notes: '',
    imageUrl: null,
  },
  {
    id: 'REQ-00118',
    customerId: 'USR-0304',
    customerName: 'Tunde Ogunleye',
    providerId: 'PRV-001',
    providerName: 'John Plumbing Services',
    serviceId: 'SVC-001',
    serviceName: 'Leak Repair',
    categoryId: 'plumber',
    description: 'Ceiling leak above the hallway after heavy rain.',
    state: 'Anambra',
    city: 'Awka',
    area: 'Umuoji',
    preferredDate: daysFromNow(-3),
    preferredTime: '16:00',
    status: REQUEST_STATUS.IN_PROGRESS,
    createdAt: hoursFromNow(-24 * 4),
    updatedAt: hoursFromNow(-3),
    rejectionReason: null,
    notes: '',
    imageUrl: null,
  },
  {
    id: 'REQ-00111',
    customerId: 'USR-0305',
    customerName: 'Segun Adeyemi',
    providerId: 'PRV-001',
    providerName: 'John Plumbing Services',
    serviceId: 'SVC-003',
    serviceName: 'Water Heater',
    categoryId: 'plumber',
    description: 'Replace a 50 litre heater.',
    state: 'Anambra',
    city: 'Awka',
    area: 'Amakwo',
    preferredDate: daysFromNow(-14),
    preferredTime: '09:30',
    status: REQUEST_STATUS.COMPLETED,
    createdAt: hoursFromNow(-24 * 18),
    updatedAt: hoursFromNow(-24 * 14),
    rejectionReason: null,
    notes: '',
    imageUrl: null,
  },
];

/* ------------------------------------------------------------------ */
/* Reviews                                                             */
/* ------------------------------------------------------------------ */

export const reviews = [
  {
    id: 'REV-301',
    requestId: 'REQ-00111',
    providerId: 'PRV-001',
    customerId: 'USR-0305',
    customerName: 'Segun Adeyemi',
    rating: 5,
    comment: 'Arrived on time and replaced the heater the same visit. Very tidy work.',
    createdAt: hoursFromNow(-24 * 13),
  },
  {
    id: 'REV-298',
    requestId: 'REQ-00088',
    providerId: 'PRV-001',
    customerId: 'USR-0306',
    customerName: 'Ngozi Okafor',
    rating: 5,
    comment: 'Sorted a stubborn leak that two other people could not find. Highly recommended.',
    createdAt: hoursFromNow(-24 * 9),
  },
  {
    id: 'REV-294',
    requestId: 'REQ-00071',
    providerId: 'PRV-001',
    customerId: 'USR-0307',
    customerName: 'Chidera Eze',
    rating: 4,
    comment: 'Good work and fair price. Arrived about 30 minutes late.',
    createdAt: hoursFromNow(-24 * 30),
  },
  {
    id: 'REV-287',
    requestId: 'REQ-00052',
    providerId: 'PRV-003',
    customerId: demoUser.id,
    customerName: demoUser.fullName,
    rating: 5,
    comment: 'Found the wiring fault quickly and explained what was wrong. Very professional.',
    createdAt: hoursFromNow(-24 * 45),
  },
];

/* ------------------------------------------------------------------ */
/* Messaging                                                           */
/* ------------------------------------------------------------------ */

export const conversations = [
  {
    id: 'CNV-001',
    requestId: 'REQ-00124',
    providerId: 'PRV-001',
    providerName: 'John Plumbing Services',
    providerAvatar: null,
    customerId: demoUser.id,
    customerName: demoUser.fullName,
    lastMessageAt: hoursFromNow(-0.03),
    unreadCount: 2,
    messages: [
      {
        id: 'MSG-001',
        senderId: demoUser.id,
        senderName: demoUser.fullName,
        senderRole: ROLES.CUSTOMER,
        body: 'Hello, I have submitted a request for a kitchen sink leak. Are you available this week?',
        createdAt: hoursFromNow(-6),
        readAt: hoursFromNow(-5.9),
      },
      {
        id: 'MSG-002',
        senderId: 'PRV-001',
        senderName: 'John Plumbing Services',
        senderRole: ROLES.PROVIDER,
        body: 'Good afternoon. I have accepted your request. I can come Saturday at 10:00 AM.',
        createdAt: hoursFromNow(-5),
        readAt: hoursFromNow(-4.9),
      },
      {
        id: 'MSG-003',
        senderId: demoUser.id,
        senderName: demoUser.fullName,
        senderRole: ROLES.CUSTOMER,
        body: 'Saturday at 10 works. Please call when you are outside.',
        createdAt: hoursFromNow(-1.2),
        readAt: hoursFromNow(-1.1),
      },
      {
        id: 'MSG-004',
        senderId: 'PRV-001',
        senderName: 'John Plumbing Services',
        senderRole: ROLES.PROVIDER,
        body: 'Noted. I will call the number on the request.',
        createdAt: hoursFromNow(-0.03),
        readAt: null,
      },
    ],
  },
  {
    id: 'CNV-002',
    requestId: 'REQ-00119',
    providerId: 'PRV-003',
    providerName: 'ABC Electric',
    providerAvatar: null,
    customerId: demoUser.id,
    customerName: demoUser.fullName,
    lastMessageAt: hoursFromNow(-1),
    unreadCount: 0,
    messages: [
      {
        id: 'MSG-010',
        senderId: demoUser.id,
        senderName: demoUser.fullName,
        senderRole: ROLES.CUSTOMER,
        body: 'I submitted a request for a socket fault. Is anyone free to inspect first?',
        createdAt: hoursFromNow(-2),
        readAt: hoursFromNow(-1.5),
      },
      {
        id: 'MSG-011',
        senderId: 'PRV-003',
        senderName: 'ABC Electric',
        senderRole: ROLES.PROVIDER,
        body: 'I will review the details and get back to you shortly.',
        createdAt: hoursFromNow(-1),
        readAt: hoursFromNow(-1),
      },
    ],
  },
  {
    id: 'CNV-003',
    requestId: 'REQ-00102',
    providerId: 'PRV-005',
    providerName: 'SparkleHome Cleaning',
    providerAvatar: null,
    customerId: demoUser.id,
    customerName: demoUser.fullName,
    lastMessageAt: hoursFromNow(-26),
    unreadCount: 0,
    messages: [
      {
        id: 'MSG-020',
        senderId: 'PRV-005',
        senderName: 'SparkleHome Cleaning',
        senderRole: ROLES.PROVIDER,
        body: 'The deep clean is complete. Thank you for choosing us.',
        createdAt: hoursFromNow(-26),
        readAt: hoursFromNow(-25),
      },
    ],
  },
];

/* ------------------------------------------------------------------ */
/* Notifications                                                       */
/* ------------------------------------------------------------------ */

export const notifications = [
  {
    id: 'NTF-01',
    type: NOTIFICATION_TYPE.NEW_MESSAGE,
    title: 'New message from John Plumbing Services',
    body: 'Noted. I will call the number on the request.',
    createdAt: hoursFromNow(-0.03),
    readAt: null,
    link: 'messages.html?conversation=CNV-001',
    audience: ROLES.CUSTOMER,
  },
  {
    id: 'NTF-02',
    type: NOTIFICATION_TYPE.REQUEST_ACCEPTED,
    title: 'Your request was accepted',
    body: 'John Plumbing Services accepted REQ-00124 for Saturday at 10:00 AM.',
    createdAt: hoursFromNow(-5),
    readAt: null,
    link: 'my-requests.html?id=REQ-00124',
    audience: ROLES.CUSTOMER,
  },
  {
    id: 'NTF-03',
    type: NOTIFICATION_TYPE.REQUEST_SUBMITTED,
    title: 'New service request',
    body: 'Ada Nwosu requested Pipe Installation in Amakwo.',
    createdAt: hoursFromNow(-1),
    readAt: null,
    link: 'request-details.html?id=REQ-00131',
    audience: ROLES.PROVIDER,
  },
  {
    id: 'NTF-04',
    type: NOTIFICATION_TYPE.REVIEW_REMINDER,
    title: 'How was your cleaning service?',
    body: 'Your service is complete. Leave a review to help other customers.',
    createdAt: hoursFromNow(-24 * 8),
    readAt: hoursFromNow(-24 * 7),
    link: 'my-requests.html?review=REQ-00102',
    audience: ROLES.CUSTOMER,
  },
];

/* ------------------------------------------------------------------ */
/* Admin data                                                          */
/* ------------------------------------------------------------------ */

export const customers = [
  { id: 'USR-0001', fullName: 'Chidi Okonkwo', email: 'chidi@example.com', state: 'Anambra', city: 'Awka', status: ACCOUNT_STATUS.ACTIVE, joinedAt: hoursFromNow(-24 * 60) },
  { id: 'USR-0301', fullName: 'Ada Nwosu', email: 'ada@example.com', state: 'Anambra', city: 'Awka', status: ACCOUNT_STATUS.ACTIVE, joinedAt: hoursFromNow(-24 * 40) },
  { id: 'USR-0302', fullName: 'Emeka Obi', email: 'emeka@example.com', state: 'Anambra', city: 'Awka', status: ACCOUNT_STATUS.ACTIVE, joinedAt: hoursFromNow(-24 * 35) },
  { id: 'USR-0304', fullName: 'Tunde Ogunleye', email: 'tunde@example.com', state: 'Anambra', city: 'Awka', status: ACCOUNT_STATUS.SUSPENDED, joinedAt: hoursFromNow(-24 * 20) },
  { id: 'USR-0306', fullName: 'Ngozi Okafor', email: 'ngozi@example.com', state: 'Lagos', city: 'Ikeja', status: ACCOUNT_STATUS.ACTIVE, joinedAt: hoursFromNow(-24 * 12) },
];

export const categories = [
  { id: 'electrician', name: 'Electrician', group: 'home', isActive: true, providerCount: 14 },
  { id: 'plumber', name: 'Plumber', group: 'home', isActive: true, providerCount: 21 },
  { id: 'cleaner', name: 'Cleaner', group: 'home', isActive: true, providerCount: 17 },
  { id: 'painter', name: 'Painter', group: 'home', isActive: true, providerCount: 9 },
  { id: 'carpenter', name: 'Carpenter', group: 'home', isActive: true, providerCount: 7 },
  { id: 'mechanic', name: 'Mechanic', group: 'automotive', isActive: true, providerCount: 12 },
  { id: 'tutor', name: 'Tutor', group: 'education', isActive: true, providerCount: 19 },
  { id: 'computer-technician', name: 'Computer Technician', group: 'technology', isActive: true, providerCount: 11 },
  { id: 'barber', name: 'Barber', group: 'personal', isActive: true, providerCount: 8 },
  { id: 'astrology', name: 'Astrology', group: 'personal', isActive: false, providerCount: 0 },
];

export const reports = [
  {
    id: 'RPT-01',
    reporterId: 'USR-0001',
    reporterName: 'Chidi Okonkwo',
    targetType: 'provider',
    targetId: 'PRV-006',
    targetName: 'Ogunleye Motors',
    reason: REPORT_REASON.FAKE_PROFILE,
    description: 'Provider has not responded to three requests and the profile photo looks like a stock image.',
    status: 'open',
    createdAt: hoursFromNow(-18),
  },
  {
    id: 'RPT-02',
    reporterId: 'USR-0301',
    reporterName: 'Ada Nwosu',
    targetType: 'review',
    targetId: 'REV-271',
    targetName: 'Review on ABC Electric',
    reason: REPORT_REASON.INAPPROPRIATE,
    description: 'Review contains abusive language.',
    status: 'open',
    createdAt: hoursFromNow(-52),
  },
  {
    id: 'RPT-03',
    reporterId: 'USR-0302',
    reporterName: 'Emeka Obi',
    targetType: 'customer',
    targetId: 'USR-0304',
    targetName: 'Tunde Ogunleye',
    reason: REPORT_REASON.POOR_CONDUCT,
    description: 'Customer repeatedly cancelled bookings at short notice.',
    status: 'resolved',
    createdAt: hoursFromNow(-24 * 6),
  },
];

export const adminStats = {
  customers: 1240,
  providers: 380,
  activeRequests: 76,
  completedServices: 2450,
  pendingRequests: 19,
  openReports: 12,
  averageRating: 4.6,
  categoriesActive: categories.filter((item) => item.isActive).length,
};

export const activityFeed = [
  { id: 'ACT-01', message: 'New provider registration', detail: 'Ogunleye Motors applied for verification', createdAt: hoursFromNow(-0.08) },
  { id: 'ACT-02', message: 'Service request completed', detail: 'REQ-00111 marked completed', createdAt: hoursFromNow(-0.3) },
  { id: 'ACT-03', message: 'Review reported', detail: 'Review REV-271 flagged for moderation', createdAt: hoursFromNow(-0.7) },
  { id: 'ACT-04', message: 'New customer registered', detail: 'Ngozi Okafor created a customer account', createdAt: hoursFromNow(-1.4) },
  { id: 'ACT-05', message: 'Category updated', detail: 'Plumber description refreshed', createdAt: hoursFromNow(-3) },
];

/** Demo credentials surfaced on the login page in mock mode. */
export const demoCredentials = {
  customer: { email: 'chidi@example.com', password: 'Password123', label: 'Customer — Chidi Okonkwo' },
  provider: { email: 'john@example.com', password: 'Password123', label: 'Provider — John Plumbing Services' },
  admin: { email: 'admin@handynaija.com', password: 'Password123', label: 'Administrator' },
};